  
name: AutoDocumentPR

on:
  push:
    branches: 
      - dev

jobs:
  dokka:
    name: Dokka
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: "Cache ~/.gradle/caches"
        uses: actions/cache@preview
        with:
          path: "~/.gradle/caches"
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle.kts') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
      - name: Configure git
        run: |
          git config --local user.email "noreply@github.com"
          git config --local user.name "GitHub"
          
      - name: Run dokka
        run: |
          ./gradlew dokka
      
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: PR for auto doc update
          signoff: false
          title: 'Update doc'
          body: |
            Update doc
            - Auto-generated 
          labels: |
            report
            automated pr
          team-reviewers: |
            owners
            maintainers

      - name: Check output
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
