name: Testing Workflow

on:
  push:
    branches: 
      - dev
      - master
  pull_request:
    branches: 
      - dev
      - master


jobs:
  test:

    runs-on: [ubuntu-18.04]

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run unit tests
      run: ./gradlew check
    - name: upload code coverage
      run: bash <(curl -s https://codecov.io/bash)
